// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensorPal.Server.Storage;

#nullable disable

namespace SensorPal.Server.Migrations
{
    [DbContext(typeof(SensorPalDbContext))]
    [Migration("20260222213540_AddApiKey")]
    partial class AddApiKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("SensorPal.Server.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("BackgroundBitrate")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NoiseThresholdDb")
                        .HasColumnType("REAL");

                    b.Property<int>("PostRollSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreRollSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("SensorPal.Server.Entities.MonitoringSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundFile")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MonitoringSessions");
                });

            modelBuilder.Entity("SensorPal.Server.Entities.NoiseEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BackgroundOffsetMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClipDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClipFile")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PeakDb")
                        .HasColumnType("REAL");

                    b.Property<long>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("NoiseEvents");
                });

            modelBuilder.Entity("SensorPal.Server.Entities.NoiseEvent", b =>
                {
                    b.HasOne("SensorPal.Server.Entities.MonitoringSession", "Session")
                        .WithMany("Events")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SensorPal.Server.Entities.MonitoringSession", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
